- name: Just ensuring the repo checkout exists
  ansible.builtin.git:
    repo: "https://{{ github_token }}@{{ item }}"
    dest: /home/ec2-user/environment/{{ item }}
    update: no
  loop: "{{ repositories }}"

- name: Recursively change ownership of a directory
  ansible.builtin.file:
    path: /home/ec2-user/environment/{{ item }}
    state: directory
    recurse: yes
    owner: ec2-user
    group: ec2-user
  loop: "{{ repositories }}"