---
- name: Install amazon-linux-extras
  become: true
  ansible.builtin.package:
    name:
      - amazon-linux-extras
      - jq
    state: present

- name: Install amazon-linux-extras
  become: true
  ansible.builtin.package:
    name:
      - python3.8
    state: present

- name: Create a symbolic link
  become: true
  ansible.builtin.file:
    src: /usr/bin/python3.8
    dest: /usr/bin/python3
    force: yes
    owner: root
    group: root
    state: link

- name: Uninstall default python3
  become: true
  ansible.builtin.package:
    name:
      - python3.x86_64
    state: absent
    
- name: Install cffi python package
  pip:
    executable: pip3
    name: 
      - cffi
      - twine
      - az-cli