---
- name: Install amazon-linux-extras
  become: true
  ansible.builtin.package:
    name:
      - amazon-linux-extras
    state: present

- command: amazon-linux-extras enable python3.8

- name: Install python3.8
  become: true
  ansible.builtin.yum:
    name:
      - python3.8
    state: present
    update_cache: yes

- name: Uninstall default python3
  become: true
  ansible.builtin.package:
    name:
      - python3.x86_64
    state: absent

- name: Create a symbolic link python3
  become: true
  ansible.builtin.file:
    src: /usr/bin/python3.8
    dest: /usr/bin/python3
    force: yes
    owner: root
    group: root
    state: link

- name: Create a symbolic link pip3
  become: true
  ansible.builtin.file:
    src: /usr/bin/pip3.8
    dest: /usr/bin/pip3
    force: yes
    owner: root
    group: root
    state: link
    
- name: Install cffi python package
  pip:
    executable: pip3
    name: 
      - cffi
      - twine
      - az-cli