- name: Install a Nginx Package
  vars:
    ansible_connection: aws_ssm
    ansible_aws_ssm_bucket_name: nameofthebucket
    ansible_aws_ssm_region: "{{ aws_region }}"
  tasks:
    - name: Test shell command
      ansible.builtin.shell: whoami